# Inserts a blank line between shell prompts
add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$character\
"""

# Replace the "❯" symbol in the prompt with "➜"
[character]
format = ""

[nodejs]
format = '[$version]($style) '
symbol = ''

[git_branch]
format = '[\(($branch)\)]($style) '
symbol = ''

[directory]
format = "[$path]($style) "
truncation_length = 1
truncation_symbol = "➜ "
